import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from './components/ApiContext';
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg[#f6f6f6] bg-red-500 text-black">
        <ProductProvider> 
          <NavBar/>
          {children}
          </ProductProvider>
       
        
        </body>
    </html>
  );
}
